version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: taxi-postgres
    environment:
      POSTGRES_DB: taxi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taxi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  trip-service:
    build: ./trip-service
    container_name: trip-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taxi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taxi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  pgdata: